### ISSUE TITLE
use fused location provider

### ISSUE THREAD

**Issue by stephanlindauer** [criticalmaps/criticalmaps-android#116]
if this conflicts with the f-droid policy, we'll have to think of a way to make it work for two falvors.

**Comment by stephanlindauer** [comment]
http://developer.android.com/training/location/index.html

**Comment by cbalster** [comment]
Since we're making constant use of the location gps and network providers, I don't think there is much potential for saving power by using the fused location provider.

**Comment by ligi** [comment]
It could help in tunnels ;-)

**Comment by cbalster** [comment]
Afaik FLP doesn't do any extrapolation either.

**Comment by stephanlindauer** [comment]
what are the advandages of using fused then?

**Comment by cbalster** [comment]
It abstracts away the difference between of GPS and network providers,
handling of accuracy and timestamps, frequency of updates etc. You only
specify an abstract requirement for your location needs and the rest is
taken care of. Besides making things a little easier it also allows the
system to optimize for battery usage by batching location updates etc.
Sinve we're polling in really short intervals and basically want the
highest precision we can get, we won't get any benefits from that. Since we
already have sufficient quality filtering of location fixes in place, I
don't see any need for introducing a dependency to play services.

**Comment by stephanlindauer** [comment]
okay i see. can we close this issue then?

**Comment by cbalster** [comment]
From my side, yes ;)

**Comment by ligi** [comment]
ack - but I would not say 100% no to play-services as a flavor ( but it should always give a play-services free flavor e.g. for fdroid ) - I think a day/night mode would be great for the app and that would be good with the new styleable maps from play-services

**Comment by stephanlindauer** [comment]
@cbalster this can be closed, am i right?

**Comment by cbalster** [comment]
Yep.
