### ISSUE TITLE
check timestamp of gps before sending outdated location

### ISSUE THREAD

**Issue by stephanlindauer** [criticalmaps/criticalmaps-android#122]
check if the location fix is older then -let's say- one minute. if it is: dont send it with the push/pull request.

**Comment by ligi** [comment]
@cbalster reasoned about using 30s in his last PR and I agree with it:

 // Average speed of the CM is ~4 m/s so anything over 30 seconds old, may already
 // be well over 120m off. So a newer fix is assumed to be always better.

But the issue is still open as far as I see publishNewLocation is only called <30s now but PullServerHandler still sends out the old location

**Comment by cbalster** [comment]
will take care of this
