### ISSUE TITLE
Reduce amount of data transferred

### ISSUE THREAD

**Issue by steve8x8** [criticalmaps/criticalmaps-android#191]
Yesterday I took part in the Fahrradsternfahrt to Berlin. During 4 hours, my phone spent almost 20 MB. I don't have a generous data plan, and this was way beyond my "daily allowance".

There seem to be multiple factors contributing to this rather large amount of data:
 - I could find no way to use offline maps (I'm using them with Locus, and c:geo, thus a newer mapsforge interrface should work)
- There seems to be no map tile caching
- The app appears to load map tiles even if it's only running in the background (I don't have proof for that, except that between two consecutive unlocks, more than 5 MB had been spent). Actually, my phone reports twice the amount of data transferred in the background compared to foreground usage (i.e. when I was zooming and panning around for other participants)!

While a typical CM will take place in a well-defined, small area, such a setup like the Sternfahrt would cover long distances and therefore would trigger more map reloads than usual.

Is there an overview what kind of data gets transmitted (sent, and received) in which situations?
I'd expect my own location to be sent every now and then (10 - 15 seconds?) but other locations, and map tiles, only pulled if there are any participants within my view window, and *none of that* while running in the background.

I'm back to Herve Renault's self-hosted location tracking service for now (which consumes <1/4 kB per my location report).

Wishlist (in decreasing order of importance to me):
- option to use off-line maps (must-have)
- no map tile loading in the background at all (important)
- reduce traffic to a minimum in bg mode (only report own location; perhaps notify of chat? - normal)
- option to opt out of chat etc.

Thanks!

**Comment by cbalster** [comment]
Hi, thanks for the feedback :)

- Tiles are cached automatically by osmdroid and stored in a database on your device. They should be on your main "SDCard"/emulated storage in "/osmdroid/tiles"

- Offline maps would be a nice feature, I agree. Until then the workaround would be to scroll around the expected areas in different zoom levels while you're on wifi. :\

- There should be no tile-loading at all, while the app is in the background. I see no possibility how, since the MapView is not updated while the app is in background. The only thing I could think of is, is that for some reason osmdroid keeps listening to location updates AND loads tiles for new locations automatically. Unlikely, but I'll look into that.

- Regarding different calls to the backend while minimized: Right now the backend does not support that, but maybe in the future we can change something here. Honestly I don't think it's high priority: After a rough calculation and assuming ~300 Users, the resulting traffic for the 4 hours you mentioned should be only around 4.2MB. And this is assuming uncompressed communication.  @stephanlindauer Is gzip enabled server-side?

Christian

**Comment by cbalster** [comment]
I just checked and that there is no loading of tiles while the app is in the background. I'm really surprised you saw 5MB of traffic in between unlocks. I'll try to do some more testing regarding the backend traffic in the next days.

**Comment by stephanlindauer** [comment]
just realized: gzip is not enabled on the new server.
changing this is a bit of a pain because the nginx config is tightly coupled to the thing that renews certs.
i'll see how i can fix this. worst case: manually renewing certs. :unamused:

**Comment by stephanlindauer** [comment]
this is fixed via using k8s + traefik as a remote proxy
