### ISSUE TITLE
Logo/icon design proposal for your project

### ISSUE THREAD

**Issue by idimummy** [criticalmaps/criticalmaps-android#215]
@stephanlindauer, I will like make a contribution to your open source project in the area of graphics. I designed a logo/icon for your application, and I need your thought about it. I believe its more descriptive to your app. This proposed logo has three major graphical component of your app. A chain design, a compass and a locator. Let me know your thought, I can always deliver on your expectation.

![criticalmaps](https://user-images.githubusercontent.com/35470411/39934884-2c8c0c58-553f-11e8-9f12-75dd1065b2d8.jpg)

I hope you'll like it and use it for your application

**Comment by stephanlindauer** [comment]
@idimummy thanks for your contribution.
let me start by saying, that this project has now a lot of people contributing and decisions like that should be made by all people involved. so what do you think @ligi @cbalster @johnjohndoe @headione @zutrinken ?
my personal opinion, ist, that i would like to keep the current one. because:
- it was made by gitti (who is an awesome illustrator from the berlin bike poloists) and i think it looks quite dope
- people already identify the app with that logo
- it fits better into all the square places where it's needed

**Comment by johnjohndoe** [comment]
@idimummy First of all, I appreciate very much that you like to contribute to this project! Thank you for your work.

With regards to replacing the [current logo](https://github.com/criticalmaps/criticalmaps-android/blob/master/app/src/main/res/drawable-nodpi/ic_launcher.png) I share the concerns which @stephanlindauer pointed out. My biggest issue with that is that an established logo acts like a **visual brand** for the "product" (value of brand recognition). Therefore, changes should be made as minimal as possible.
I kind of remember there was design work done in 2017 and discussed on Slack ... not sure about the outcome. Anyone?

If one decides to replace the logo with a new logo then a good strategy is to run an **A/B test** with the users to measure how it gets accepted.
